############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1


[[main]]
weight = 2
name = "Dogs"
url = "sale"

[[main]]
weight = 3
name = "Gallery"
url = "gallery"

[[main]]
name = "About Us/Apply For A Puppy"
url = "contact/"
weight = 4

# footer menu

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

[[footer]]
name = "Terms and Conditions"
url = "terms-and-conditions/"
weight = 4
